from django.urls import path
from.import views

urlpatterns=[path("path1/",views.signup,name="signup"),
             path("path2/",views.login,name="login"),
             path("path3/",views.personal,name="personal"),
             path("path4/",views.personaldata,name="personaldata"),
             path("path5/",views.education,name="education"),
             path("path6/",views.educationdata,name="educationdata"),
             path("path7/",views.medical,name="medical"),
             path("path8/",views.medicaldata,name="medicaldata"),
             path("path9/",views.account,name="account"),
             path("path10/",views.accountdata,name="accountdata"),
             path("path11/",views.user_logout,name="user_logout"),
             path("path12/<id2>",views.personaledit,name="personaledit"),
             path("path13/<id1>",views.delete,name="delete"),
             path("path14/",views.employee,name="employee"),
             path("path15/",views.employeedata,name="employeedata"),
             path("path16/<id3>",views.educationedit,name="educationedit"),
             path("path17/<id8>",views.edudelete,name="edudelete"),
             path("path18/<id20>",views.accountedit,name="accountedit"),
             path("path19/<id25>",views.acdelete,name="acdelete"),
             path("path20/<id100>",views.medicaledit,name="medicaledit"),
             path("path21/<id99>",views.meddelete,name="meddelete"),
             path("path22/<id33>",views.employeedit,name="employeedit"),
             path("path23/<id35>",views.emdelete,name="emdelete"),
             path("",views.home,name="home"),
             path("path30/",views.home,name="home"),
             path("path24/",views.about,name="about"),
             path("path40/",views.success,name="success"),
             path("path41/",views.invalid,name="invalid"),
             path("path26/",views.update,name="update"),
             path("path27/",views.profile,name="profile"),
             path("path28/",views.deleted,name="deleted"),
             path("path29/",views.submit,name="submit")
             ]