# Generated by Django 5.1.2 on 2024-12-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_accounttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('work_email', models.EmailField(max_length=254, unique=True)),
                ('work_phone', models.CharField(max_length=15)),
                ('date_of_joining', models.DateField()),
                ('employment_type', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('office_location', models.CharField(max_length=100)),
            ],
        ),
    ]
